services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tasks
      POSTGRES_USER: hmcts
      POSTGRES_PASSWORD: hmcts
    ports:
      - "5433:5432"
    volumes:
      - pgdata-hmcts:/var/lib/postgresql/data

volumes:
  pgdata-hmcts: